$font = Nunito ExtraBold

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = ~/Downloads/images/lakeside-pink-sky-sunset.png
    # blur_passes = 2
    # blur_size = 2
    fit_mode = cover
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3

    position = 0, 200
    halign = center
    valign = bottom

    outer_color = rgb(e15c95)
    check_color = rgb(60ff26)
    fail_color = rgb(ff4040) rgb(d42424) #90deg
    inner_color = rgba(100, 100, 100,0.4)
    shadow_passes = 1
    shadow_size = 4

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 5

    font_family = Nunito Semibold
    placeholder_text = Password
    fail_text = Nice Try

    dots_spacing = 0.3
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M")"
    font_size = 55
    font_family = $font

    position = 0, 200
    halign = center
    valign = center
}
# USER
# label {
#     monitor =
#     text = $USER
#     color = #e15c95
#     font_size = 40
#     font_family = Victor Mono Bold Oblique
#     position = 0, 300
#     halign = center
#     valign = bottom
# }
#
# shape {
#     monitor =
#     size = 360, 60
#     color = rgba(1, 1, 1, 0.5) # no fill
#     rounding = -1 # circle
#     border_size = 4
#     border_color = rgba(0, 207, 230, 1.0)
#
#     position = 0, 300
#     halign = center
#     valign = bottom
# }
