[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]

image = [
  { run = 'imv "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image" },
]

[preview]
wrap = "yes"
tab_size = 3
max_width = 50000
max_height = 50000
cache_dir = ""

[mgr]
ratio = [1, 2, 3]

prepend_keymap = [
    { on = "<Enter>", run = "plugin --sync smart-enter", desc = "Smart open" },
]
